### ISSUE TITLE
[Bug] Text wrap

### ISSUE THREAD

**Issue by zaptot** [zaptot/testing_bsu#1]
Воспроизведение:
    1. Открываем сайт https://cs-training-task.qulix.com/trainingtask2/projects
    2.  Постепенно меняем ширину окна браузера

Полученный результат:
    При определённой ширине экрана некоторые элементы будут переноситься на новую строку частями (можно увидеть на прикреплённом скриншоте)

Ожидаемые результат:
    Переноситься должны элементы целиком, а не частями
<img width="178" alt="Screen Shot 2019-04-28 at 5 30 48 PM" src="https://user-images.githubusercontent.com/22732993/56865866-73056b00-69db-11e9-886b-e07d32527220.png">

**Comment by vliplianina** [comment]
Принято.

Рекомендация: оформлять заголовок и описание на одном языке. Для данного проекта удобнее на русском.
