### ISSUE TITLE
нет возможности заасайнить задачу на нескольких сотрудников

### ISSUE THREAD

**Issue by zaptot** [zaptot/testing_bsu#11]
Воспроизведение:
1. Зайти на страницу задачи
2. Выбрать любую из существующих задач
3. Нажать кнопку изменить для выбранной задачи
4. Выбрать сотрудника

Полученный результат: 
Можно выбрать только одного сотрудника

Ожидается:
Должна быть возможность добавлять нескольких людей на одну задачу

**Comment by vliplianina** [comment]
Принято.
