### ISSUE TITLE
если задача заасайнена на юзера, а юзера удалить, то появятся задачи ни на кого не заасайненные

### ISSUE THREAD

**Issue by zaptot** [zaptot/testing_bsu#13]
Вопроизведение:
1. Перейти во вкладки Персоны и создать тестовую персону
2. Перейти во вкладку задачи и создать тестовую задачу заасайнив его на прежде созданную тестовую персону
3. Перейти во вкладку Персоны и удалить нашу персону

Полученный результат:
Перейдя во вкладку Задачи видим задачу без выполняющего её человека

Ожидается:
Обдумать механизм, который будет решать эту проблему.

Возможное решение:
После удаления персоны все незавершенные задачи, которые заасайнены на него асайнить на его лиды

**Comment by zaptot** [comment]
<img width="1315" alt="Screen Shot 2019-05-11 at 1 58 12 AM" src="https://user-images.githubusercontent.com/22732993/57560688-46186700-7390-11e9-80e2-ec5ab6158985.png">

**Comment by vliplianina** [comment]
Принято.
