### ISSUE TITLE
[Bug] creating new project form bad markup

### ISSUE THREAD

**Issue by zaptot** [zaptot/testing_bsu#2]
Воспроизведение:
    1. Открыть вкладку проекты
    2. Нажать кнопку добавить
Полученный результат: 
    Видим, что форма создание нового проекта отображается некорректно
Ожидаемый результат:
    Форма должна отображаться как и при добавлении новых задач или персон

**Comment by vliplianina** [comment]
Замечания:
1) Не описано, что именно отображается некорректно и не предоставлен скриншот.
2) Заголовок не отражает суть дефекта. Согласно заголовку, дефект заключается в создании нового проекта.

Необходимо исправить.

**Comment by zaptot** [comment]
<img width="1665" alt="Screen Shot 2019-04-30 at 1 08 42 AM" src="https://user-images.githubusercontent.com/22732993/56930292-db8c3f00-6ae4-11e9-95e8-ccabf1657dab.png">

**Comment by vliplianina** [comment]
Принято.
Рекомендации: точнее описывать ожидаемый результат и предоставлять более информативный скриншот. Например, на скриншоте продемонстрировать и форму создания проекта, и форму создания задачи, чтобы можно было сразу увидеть разницу в отображении и не выполнять дополнительных действий для исследования дефекта.
