### ISSUE TITLE
[Improvment] Delete id field while creating new project, task, employee

### ISSUE THREAD

**Issue by zaptot** [zaptot/testing_bsu#3]
Шаги: 
1. Открыть вкладку Проекты, Задачи, Персоны
2. Нажать кнопку Добавить

Получено:
Форма, в которой отображается поле идентификатор, которое нельза заполнить

Ожидается:
Для удобства использования удалить данное поле из формы, так как его всё равно нельзя заполнять

**Comment by vliplianina** [comment]
Принято.

**Comment by vliplianina** [comment]
Приоритет понижен до minor, т.к. наличие/отсутствие поля не влияет на функциональность
