### ISSUE TITLE
[Improvment] Delete id field while creating new employee

### ISSUE THREAD

**Issue by zaptot** [zaptot/testing_bsu#4]
Шаги: 
1. Открыть вкладку Персоны
2. Нажать кнопку Добавить

Получено:
Форма, в которой отображается поле идентификатор, которое нельзя заполнить

Ожидается:
Для удобства использования удалить данное поле из формы, так как его всё равно нельзя заполнять

**Comment by vliplianina** [comment]
Объединить с issue #3 и закрыть. Отмечаю как дубликат.

**Comment by vliplianina** [comment]
Приоритет понижен до minor, т.к. наличие/отсутствие поля не влияет на функциональность
