### ISSUE TITLE
[Improvment] Delete id field while creating new task

### ISSUE THREAD

**Issue by zaptot** [zaptot/testing_bsu#5]
Шаги: 
1. Открыть вкладку Задачи
2. Нажать кнопку Добавить

Получено:
Форма, в которой отображается поле идентификатор, которое нельза заполнить

Ожидается:
Для удобства использования удалить данное поле из формы, так как его всё равно нельзя заполнять

**Comment by vliplianina** [comment]
Объединить с issue #3 и закрыть. Отмечаю как дубликат.
