### ISSUE TITLE
[Bug] Changing project form bad markup

### ISSUE THREAD

**Issue by zaptot** [zaptot/testing_bsu#7]
Воспроизведение:
1. перейти на категорию проектов
2. нажать кнопку изменить около любого из существующих проектов

Полученный результат:
Форма отображается в окне с таблицей, вся вёрстка ломается

Ожидаемый результат:
Форма открывается в отдельном окне

**Comment by vliplianina** [comment]
Замечания:
1) Заголовок не отражает суть дефекта, только указывает на раздел. Нужно переформулировать.
2) Нужен скриншот

**Comment by zaptot** [comment]
<img width="1677" alt="Screen Shot 2019-04-30 at 1 10 26 AM" src="https://user-images.githubusercontent.com/22732993/56930267-c8796f00-6ae4-11e9-97b8-4510d2e77bc0.png">

**Comment by vliplianina** [comment]
Принято. Описание ок.

Но ожидаемый результат неверный с функциональной точки зрения.
Форма создания и редактирования проекта должна содержать список задач, принадлежащих проекту. Список задач реализован в виде таблицы. При редактировании проекта должна быть возможность отредактировать / добавить задачи, принадлежащие проекту. Поэтому если таблица со списком проектов будет отсутствовать - это будет критический дефект.
