### ISSUE TITLE
Уточнить необходимость отображения поля идентификатор в формах создания/редактирования проекта

### ISSUE THREAD

**Issue by zaptot** [zaptot/testing_bsu#8]
Просьба уточнить необходимость элемента идентификатор в форме создания/редактирования проекта.
Так как пользователь не может заполнять это поле самостоятельно, а оно генерируется автоматически, то необходимость его отображения стоит под вопросом.
Возможное решение:
Можно удалить эту колонку в форме и изменить название формы на "Создание проекта #{id}"/"Редактирование проекта #{id}"

**Comment by vliplianina** [comment]
Идентификатор необходим согласно требованиям
Нужен как минимум для распознавания необходимой записи в случае полного совпадения остальных атрибутов записи. 

Обращаю внимание, что запросы на уточнение требований нужно оформлять в репозитории команды, чтобы другие участники видели ответ:  https://github.com/vliplianina/team-9b-volunteers/issues
 
Данный вопрос предлагаю не переносить, т.к. указано явное требование и настоящее обращение может быть оформлено запросом на улучшение.
